// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40t8qV6rmQUKww21BpaiIu396vNGcYlM',
    appId: '1:583315886567:web:786f303e2c63348e68ed42',
    messagingSenderId: '583315886567',
    projectId: 'laundryonapp-43117',
    authDomain: 'laundryonapp-43117.firebaseapp.com',
    storageBucket: 'laundryonapp-43117.appspot.com',
    measurementId: 'G-BS2HECNXVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7U6mQe3EpMVgPVV9BYBicTGFjZH8kJHo',
    appId: '1:583315886567:android:106b693e9f0850d868ed42',
    messagingSenderId: '583315886567',
    projectId: 'laundryonapp-43117',
    storageBucket: 'laundryonapp-43117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC478uYMrkDRWDwSTnxywpdxMClmeoaAlo',
    appId: '1:583315886567:ios:4f74c3c3a9d947c068ed42',
    messagingSenderId: '583315886567',
    projectId: 'laundryonapp-43117',
    storageBucket: 'laundryonapp-43117.appspot.com',
    iosBundleId: 'com.example.laundryonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC478uYMrkDRWDwSTnxywpdxMClmeoaAlo',
    appId: '1:583315886567:ios:a69b89381bcdf05168ed42',
    messagingSenderId: '583315886567',
    projectId: 'laundryonapp-43117',
    storageBucket: 'laundryonapp-43117.appspot.com',
    iosBundleId: 'com.example.laundryonapp.RunnerTests',
  );
}
